### ISSUE TITLE
Compile error after update state v0.3.1 -> v0.3.2

### ISSUE THREAD

**Issue by fluxxu** [SergioBenitez/state#2]
```
cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating futures v0.1.15 -> v0.1.16
    Updating futures-cpupool v0.1.5 -> v0.1.6
    Updating gcc v0.3.53 -> v0.3.54
    Updating itoa v0.3.3 -> v0.3.4
    Updating ordermap v0.2.11 -> v0.2.12
    Updating state v0.3.1 -> v0.3.2
    Updating yansi v0.3.3 -> v0.3.4
```

```
cargo build --all
 Downloading itoa v0.3.4
 Downloading gcc v0.3.54
 Downloading futures v0.1.16
 Downloading futures-cpupool v0.1.6
 Downloading yansi v0.3.4
 Downloading ordermap v0.2.12
 Downloading state v0.3.2
   Compiling ordermap v0.2.12
   Compiling itoa v0.3.4
   Compiling gcc v0.3.54
   Compiling state v0.3.2
   Compiling yansi v0.3.4
   Compiling futures v0.1.16
error[E0493]: destructors in constant functions are an unstable feature
  --> C:\Users\fluxx\.cargo\registry\src\github.com-1ecc6299db9ec823\state-0.3.2\src\container.rs:95:9
   |
95 | /         Container {
96 | |             init: Init::new(),
97 | |             map: UnsafeCell::new(0 as *mut _),
98 | |             mutex: AtomicUsize::new(0)
99 | |         }
   | |_________^
   |
   = help: in Nightly builds, add `#![feature(drop_types_in_const)]` to the crate attributes to enable

error[E0493]: destructors in constant functions are an unstable feature
  --> C:\Users\fluxx\.cargo\registry\src\github.com-1ecc6299db9ec823\state-0.3.2\src\storage.rs:70:9
   |
70 | /         Storage {
71 | |             _phantom: PhantomData,
72 | |             item: UnsafeCell::new(0 as *mut T),
73 | |             init: Init::new()
74 | |         }
   | |_________^
   |
   = help: in Nightly builds, add `#![feature(drop_types_in_const)]` to the crate attributes to enable

error: aborting due to 2 previous errors

error: Could not compile `state`.
```

**Comment by fluxxu** [comment]
Fixed after upgrading rust to 2017-09-16.
I guess this is not an issue nor a breaking change because we are using nighly! 😄
